circles:
  num-features: 2
  synthetic-bool: true
  categorical-features:
  numerical-features:
    - 0
    - 1

spheres:
  num-features: 3
  synthetic-bool: true
  categorical-features:
  numerical-features:
    - 0
    - 1
    - 2

alternate_stripes:
  num-features: 2
  synthetic-bool: true
  categorical-features:
  numerical-features:
    - 0
    - 1

phoneme:
  num-features: 6
  synthetic-bool: false
  categorical-features:
    - 5
  numerical-features:
    - 0
    - 1
    - 2
    - 3
    - 4