circles:
  num_features: 2
  synthetic_bool: true
  categorical_features:
  numerical_features:
    - 0
    - 1

spheres:
  num_features: 3
  synthetic_bool: true
  categorical_features:
  numerical_features:
    - 0
    - 1
    - 2

alternate_stripes:
  num_features: 2
  synthetic_bool: true
  categorical_features:
  numerical_features:
    - 0
    - 1

phoneme:
  num_features: 6
  synthetic_bool: false
  categorical_features:
    - 5
  numerical_features:
    - 0
    - 1
    - 2
    - 3
    - 4

abalone:
  num_features: 8
  synthetic_bool: false
  categorical_features:
    - 0
  numerical_features:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
