- dataset: "circles"
  num-features: 2
  synthetic-bool: true
  contains-categorical: false
  
- dataset: "spheres"
  num-features: 3
  synthetic-bool: true
  contains-categorical: false
  
- dataset: "alternate_stripes"
  num-features: 2
  synthetic-bool: true
  contains-categorical: false
  
- dataset: "phoneme"
  num-features: 6
  synthetic-bool: false
  contains-categorical: true